platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Overcoat', :subspecs => ['PromiseKit', 'Social', 'CoreData'], :path => '../../Overcoat.podspec'
pod 'PromiseKit/Accounts'
pod 'TGRDataSource'
pod 'libextobjc'
pod 'AFNetworking'
pod 'Mantle', '~> 2.0'
